### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [rstacruz/flatdoc#100]
Hi, is this project still maintained or are you looking for maintainers?

**Comment by thejohnha** [comment]
14 days no response - that doesn't sound good. I am trying to decide whether to use this project, but if no one is maintaining it, that's not so nice...

**Comment by rstacruz** [comment]
Hey there! Happy to take in maintainers - anyone want to volunteer?

**Comment by DanielRuf** [comment]
I would also suggest to move the repo to an org account to make this easier for all or are there good reasons against this?

**Comment by blikblum** [comment]
I volunteer to maintain it.

#102  already brings the project to an usable state.

Somethings i plan:

In short term:
 - add dark and slate theme
 - update default theme design
 - Investigate improve loading by using link with rel=preload

In mid term:
 - Remove jquery dependency
 - Use CSS properties to easily configure theme

**Comment by blikblum** [comment]
@rstacruz do you have any opinion about my offer to maintain this project?
