### ISSUE TITLE
Tables and <pre> section side by side

### ISSUE THREAD

**Issue by hellogds** [rstacruz/flatdoc#41]
Hi, flatdoc is great.. thanks for open sourcing..

I've an issue with `<table>` and `<pre>` section being not aligned properly side by side as show in the picture..
![image](https://cloud.githubusercontent.com/assets/4985701/4098503/c0ee603c-3025-11e4-84db-ce769e21e890.png)

i expect them to be side by side like other `<p>` and `<pre>` section like

![image](https://cloud.githubusercontent.com/assets/4985701/4098520/386cd0d4-3027-11e4-8ff5-46baf38e00b2.png)

even in above image, i expect `<pre>` section to be aligned with first `<p>` 

I would love to modify this by myself but i don't know CSS/HTML much. please suggest how to achieve this.
Also I'm not sure whether current behavior is intended or not.

regards

**Comment by vahe** [comment]
Take a look at #49 for a quick fix for `table` tags, it had been bugging me for some time too. To align `p` blocks, put your code block after the first paragraph. The only issue with that is if your code is too long and you end up with a lot of whitespace between paragraphs.

**Comment by cjthomp** [comment]
Yea, running into this myself. 

The huge gap is ugly, is there a way to enforce floating on specific paragraphs?
