### ISSUE TITLE
Getting 403 (Forbidden)

### ISSUE THREAD

**Issue by malinin13** [rstacruz/flatdoc#42]
Hi! I'm trying to create a custom theme, so I downloaded that starting html file and entered rstacruz/flatdoc to USER/REPO and began styling it. I'm getting 403 (Forbidden) error, when refreshing the page after 10-20 minutes of using. I changed repo and user to other and it worked. But after 10 minutes I got the same error. What is it? Is it GitHub blocking my access to any repo?

**Comment by rstacruz** [comment]
yes, github has rate limiting. you can fetch up to 60 times per hour.

https://developer.github.com/v3/#rate-limiting
