### ISSUE TITLE
"Getting Started" template on front page doesn't match downloaded version / doesn't work as is

### ISSUE THREAD

**Issue by gimbo** [rstacruz/flatdoc#7]
Just to let you know: I hit a confusion trying out flatdoc today.  I copied/pasted the ["Getting Started snippet"](http://ricostacruz.com/flatdoc/#getting-started) from the flatdoc front page, and couldn't get it to work.  I then realised that the download link in that section of the page gives you a different version, which **did** work for me, and by comparing the two, I realised that what was missing from the snippet I'd copied/pasted was `class='content'` on the `flatdoc-content` div.  (I'm using Google Chrome 27.0.1453.110 under OSX 10.7.5, btw.)

Just thought you might like to know.

**Comment by rstacruz** [comment]
yeah i figured it might confuse someone, sorry about that. i did mention there that it was not exact—i meant to place it these for illustration purposes only.

**Comment by rstacruz** [comment]
Anyway, the one on the readme/page more closely matches the "blank" template, which is intended for the use of anyone who wants to do custom CSS:

https://github.com/rstacruz/flatdoc/tree/gh-pages/templates/blank.html

**Comment by rstacruz** [comment]
Updated.
