### ISSUE TITLE
provide a "latest" tag 

### ISSUE THREAD

**Issue by jandob** [rstacruz/flatdoc#74]
Providing a "latest" tag would make it possible to link to `https://cdn.rawgit.com/rstacruz/flatdoc/latest/flatdoc.js` in the template. So new versions are used automatically.

**Comment by rstacruz** [comment]
that wouldn't work; cdn.rawgit.com will cache the file and it'll serve the same file even if it changes. if that's the use case you're after, there's `rawgit.com` (without `cdn`) and the `gh-pages` branch, but I wouldn't recommend that (rawgit says not to do it, and dynamically linking against the latest version might break things in the future).

**Comment by jandob** [comment]
Ok, i see i didn't now their caching was permanent. 
Thanks for the answer.
