### ISSUE TITLE
Why is this a client-side lib?

### ISSUE THREAD

**Issue by sgoumaz** [rstacruz/flatdoc#9]
Am I missing something in not understanding why this isn't a static site generator instead? The client-side generation makes it pretty useless to me… 
- slow (rendering can be lightning fast, it won't beat no rendering at all)
- no option to speed up serving with a CDN
- harder to develop (every line of code must work cross-browser)
- no JS = no doc at all
- no true client-specific benefit I can see (yes there's no need to redeploy the doc site when your doc contents change, but for the vast majority of cases I imagine a simple deployment script makes this painless)

So… would you consider making it a build-time CLI tool/Grunt task?

**Comment by ericclemmons** [comment]
I don't see what the big deal is.  This is pretty much just _progressive enhancement_ for your existing `README.md`.  Github Pages already has great project generator that would meet all of your needs.

Plus, if you want to make it SEO-friendly or target the non-essential portion of Github users that have Javascript _off_, you can use PhantomJS to render & capture the output as part of your build script.

**Comment by sgoumaz** [comment]
Thanks for the clarification. No big deal… I had hopes this was more than a README prettifier, and it definitely could be.

BTW the GH pages generator doesn't seem at all flexible enough for us (single page, no easy theme customization, etc.). Thanks for suggesting PhantomJS though (but then other solutions like DocPad are probably simpler).
